vich_uploader:
    db_driver: orm

    mappings:
        product:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 
            inject_on_load:     false
            delete_on_remove : false
            delete_on_update: false